baseURL = "http://meccanikinds.github.io/"
languageCode = "it"

title = "Common Grounds"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
#externalTitle = "Common Grounds"
sidebarColor = "red"
#default, green, purple, pink, red, cyan, blue, grey, orange.
customCss = []

[markup.goldmark.renderer]
unsafe= true

[[menu.shortcuts]]
name = "Instagrounds"
url = "www.instagram.com/meccanikinds"
weight = 10
